Adding support for weighted histograms
umami-hep/puma pull request #86
Opened 2022-06-29 14:09 UTC by jobirk

## Summary

This pull request introduces the following changes

* Adding support for weighted histograms by adding an optional `weights` argument to `puma.Histogram`

Relates to the following issues

* Closes #55 

### Notes
The uncertainty is calculated per bin via the square root of the sum of squared weights in that bin:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/46069353/177321381-4f9bec99-997f-4b2c-8704-2573dd033861.png">

## Conformity
- [x] [Changelog entry](https://github.com/umami-hep/puma/blob/main/changelog.md)
- [x] [Documentation](https://umami-hep.github.io/puma/)

2022-07-05 12:56 UTC, jobirk commented on examples/plot_weighted_histograms.py
> +hist_plot.savefig("histogram_weighted.png")
The output will look like this:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/46069353/177332665-7ecc6e95-c17e-43ea-bc00-8f9d2ab56a74.png">

2022-07-20 14:20 UTC, manuguth requested changes

2022-07-20 15:52 UTC, manuguth commented on puma/utils/histogram.py
> +        counts = save_divide(counts, float(np.sum(weights)), 0)
to only calculate the sum of weights once, I would define a variable here

2022-07-21 16:58 UTC, manuguth approved these changes

2022-07-21 16:58 UTC, merged